### ISSUE TITLE
Plz give me the private Repository For ServerStats bot 

### ISSUE THREAD

**Issue by RXNationGMG** [ZixeSea/ServerStats#4]
Plz do it like ur bot

**Comment by ZixeSea** [comment]
There is already a repo for the bot but it's set to private.

**Comment by RXNationGMG** [comment]
Just give me the private repository plz ok

**Comment by ZixeSea** [comment]
Why would I give you access to a private repo for no reason

**Comment by RXNationGMG** [comment]
@ZixeSea Because I Need To Clone The Bot & I'll Put A Little Edit About Ur Bot Now Just Plz Give Me The Repo Plz :(
